PIS/models/asignacion.py
class Asignacion:
    def __init__(self):
        self.__id = 0
        self.__idMateria = None
        self.__idDocente = None

    @property
    def _id(self):
        return self.__id

    @_id.setter
    def _id(self, value):
        self.__id = value

    @property
    def _idMateria(self):
        return self.__idMateria

    @_idMateria.setter
    def _idMateria(self, value):
        self.__idMateria = value

    @property
    def _idDocente(self):
        return self.__idDocente

    @_idDocente.setter
    def _idDocente(self, value):
        self.__idDocente = value

    @property
    def serializable(self):
        return {
            "id": self._id,
            "idMateria": self._idMateria,
            "idDocente": self._idDocente
        }

    @classmethod
    def deserializar(cls, data):
        asignacion = Asignacion()
        asignacion._id = data.get("id", 0)
        asignacion._idMateria = data.get("idMateria")
        asignacion._idDocente = data.get("idDocente")
        return asignacion

PIS/routes/router.py
from datetime import datetime
from controllers.cursaDaoControl import CursaDaoControl
from models.cursa import Cursa
from models.docente import Docente
from models.materia import Materia
from models.estudiante import calculate_averages, load_data, load_excel_data, save_data
from controllers.estudianteDaoControl import (EstudianteDaoControl,filter_students,generate_chart,)
from flask import Blueprint, app, current_app, g, jsonify, render_template, redirect, request, flash, abort, send_file, session, url_for
from controllers.asignacionDaoControl import AsignacionDaoControl
from controllers.connecction.connection import Connection
from controllers.personaDaoControl import PersonaDaoControl
from flask_login import logout_user, login_required, login_user, LoginManager # type: ignore
from models.Modelcuenta import ModelCuenta
from models.cuenta import Cuenta
from controllers.docenteDaoControl import DocenteDaoControl
from controllers.materiaDaoControl import MateriaDaoControl
from werkzeug.utils import secure_filename
from fpdf import FPDF # type: ignore
import pandas as pd # type: ignore
import json
import os



router = Blueprint('router', __name__)

@router.route('/')
def home():
    return redirect("/login")

@router.route('/login', methods=['POST', 'GET'])
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        cuenta = Cuenta(0, username, password)
        logged_user = ModelCuenta.login(g.db, cuenta)
        if logged_user:
            if logged_user.clave:
                login_user(logged_user)
                if logged_user.rol == 'admin':
                    return redirect("/login/moduloAdmin")
                elif logged_user.rol == 'docente':
                    return redirect("/login/moduloDocentes")
                elif logged_user.rol == 'encargado':
                    return redirect("/login/moduloEncargado")
                else:
                    flash("Rol no encontrado")
            else:
                flash("Usuario no encontrado")
        else:
            flash("Usuario o contraseña incorrectos")
    return render_template("tempsLogin/auth/login.html")

@router.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect('/login')


#---------------MODULO DE ADMIN-----------------
@router.route("/login/moduloEncargado")
def moduloEncargado():
    return render_template("tempsFranco/index.html")

@router.route('/login/moduloAdmin')
def moduloAdmin():
    return render_template('tempsAdmin/docente/accion.html')

@router.route("/sala")
# @login_required
def sala():
    return render_template("tempsMensajes/sala.html")


# ------------------------Sección de asignaciones----------------------------------------------------------------
@router.route('/asignarMaestro', methods=['GET', 'POST'])
def asignarMaestro():
    if request.method == 'POST':
        docente_id = request.form.get('docente')
        materia_id = request.form.get('materia')
        print(f"Docente ID: {docente_id}, Materia ID: {materia_id}")
        if not docente_id or not materia_id :
            print("Error: Docente ID o Materia ID está vacío.")
            return redirect('/asignarMaestro', code=302)
        connection = Connection()
        connection.connect()
        asignacion_control = AsignacionDaoControl(connection)
        try:
            asignacion_control.save_asignacion(docente_id, materia_id)
        except Exception as e:
            print(f"Error al guardar asignación: {e}")
        finally:
            connection.close()
        return redirect('/asignarMaestro', code=302)
    connection = Connection()
    connection.connect()
    docente_control = DocenteDaoControl(connection)
    docentes = docente_control._lista
    materia_control = MateriaDaoControl(connection)
    materias = materia_control._lista
    query = """
        SELECT 
            a.ID AS ASIGNACION_ID, 
            d.nombre AS DOCENTE_NOMBRE, 
            m.nombre AS MATERIA_NOMBRE,
            m.ciclo AS CICLO_NOMBRE
        FROM 
            ASIGNACION a
        JOIN 
            DOCENTE d ON a.DOCENTE_ID = d.ID
        JOIN 
            MATERIA m ON a.MATERIA_ID = m.ID
    """
    try:
        cursor = connection.execute(query)
        asignaciones = cursor.fetchall()
        print(f"Asignaciones recuperadas: {asignaciones}")
    except Exception as e:
        print(f"Error al recuperar asignaciones: {e}")
        asignaciones = []
    connection.close()
    return render_template('tempsAdmin/gestion/asignacion.html', docentes=docentes, materias=materias, asignaciones=asignaciones, cursos=cursos)
#------------------------Sección de Cursos----------------------------------------------------------------
#acciones de cursos
@router.route('/cursos')
def cursos():
    connection = Connection()
    connection.connect()
    cursa_control = CursaDaoControl(connection)
    cursos = cursa_control._lista
    connection.close()
    return render_template('tempsAdmin/gestion/cursos.html', cursos=cursos)

#------------------------Sección de Docentes----------------------------------------------------------------
#acciones de docente
@router.route('/accionDocente')
def ver_opcionesDocentes():
    return render_template('tempsAdmin/docente/accion.html')

@router.route('/registrarDocentes')
def ver_guardar():
    return render_template('tempsAdmin/docente/registrar.html')

#LISTA DE DOCENTES
@router.route('/listaDocentes')
def ver_docentes():
    connection = Connection()
    connection.connect()
    docente_control = DocenteDaoControl(connection)
    docentes = docente_control._lista 
    connection.close()
    print(f"Docentes List: {docentes}")  
    return render_template('tempsAdmin/docente/lista.html', lista=docentes)

#MOSTRAR LISTA DE DOCENTES
@router.route('/docentes/ver')
def ver():
    return render_template('tempsAdmin/docente/registrar.html')

#guardar docentes
@router.route('/registrarDocentes/guardar', methods=['POST'])
def guardar_docentes():
    connection = Connection()
    connection.connect()
    dc = DocenteDaoControl(connection)
    nuevo_docente = Docente()
    nuevo_docente._nombre = request.form.get('nombre')
    nuevo_docente._apellido = request.form.get('apellido')
    fecha_str = request.form.get('fecha')
    try:
        fecha_obj = datetime.strptime(fecha_str, '%Y-%m-%d').date()  # Obtener solo la parte de la fecha
        nuevo_docente._fecha = fecha_obj
    except ValueError:
        print("Error: La fecha debe estar en formato YYYY-MM-DD")
        return redirect('/registrarDocentes', code=302)  # Redirigir en caso de error en el formato de la fecha
    nuevo_docente._telefono = request.form.get('telefono')
    nuevo_docente._correo = request.form.get('correo')
    nuevo_docente._genero = request.form.get('genero')
    nuevo_docente._tipoIdentificacion = request.form.get('tipoIdentificacion')
    nuevo_docente._tituloCuartoNivel = request.form.get('tituloCuartoNivel')
    nuevo_docente._especialidad = request.form.get('especialidad')
    nuevo_docente._cubiculo = request.form.get('cubiculo')
    dc._docente = nuevo_docente
    dc.save  
    connection.close()

    return redirect('/listaDocentes', code=302)

#editar docentes
@router.route('/registrarDocentes/editar/<int:id>', methods=['GET'])
def editar(id):
    connection = Connection()
    connection.connect()
    dc = DocenteDaoControl(connection)
    docente = dc._get(id)
    if not docente:
        connection.close()
        return redirect('/listaDocentes', code=302)
    connection.close()
    return render_template('tempsAdmin/docente/editar.html', docente=docente)

#modificar docentes
@router.route('/registrarDocentes/modificar', methods=['POST'])
def modificar():
    connection = Connection()
    connection.connect()
    dc = DocenteDaoControl(connection)
    data = request.form
    pos = int(data["id"]) 
    
    docente = dc._get(pos)
    if not docente:
        print(f"Error: No se encontró el docente con ID {pos}")
        connection.close()
        return redirect('/listaDocentes', code=302)
    
    docente._nombre = request.form.get('nombre')
    docente._apellido = request.form.get('apellido')
    fecha_str = request.form.get('fecha')
    try:
        fecha_obj = datetime.strptime(fecha_str, '%Y-%m-%d').date()
        docente._fecha = fecha_obj
    except ValueError:
        print("Error: La fecha debe estar en formato YYYY-MM-DD")
        connection.close()
        return redirect('/listaDocentes', code=302)
    
    docente._telefono = request.form.get('telefono')
    docente._correo = request.form.get('correo')
    docente._genero = request.form.get('genero')
    docente._tipoIdentificacion = request.form.get('tipoIdentificacion')
    docente._tituloCuartoNivel = request.form.get('tituloCuartoNivel')
    docente._especialidad = request.form.get('especialidad')
    docente._cubiculo = request.form.get('cubiculo')
    dc._docente = docente
    dc.merge(pos)
    connection.close()
    return redirect("/listaDocentes", code=302)


#eliminar docentes
@router.route('/registrarDocentes/eliminar/<int:id>', methods=['POST'])
def eliminar(id):
    connection = Connection()
    connection.connect()
    dc = DocenteDaoControl(connection)                  
    try:
        dc._delete(id)
        connection.connection.commit()
        response = {"success": True}
    except Exception as e:
        print(f"Error al eliminar el docente con ID {id}: {e}")
        connection.connection.rollback()
        response = {"success": False, "error": str(e)}
    finally:
        connection.close()
    
    return jsonify(response)


#----------------------------------SECCION MATERIA------------------------------------------------------

@router.route('/accionMateria')
def ver_opcionesMaterias():
    return render_template('tempsAdmin/materia/accionMateria.html')

#MOSTRAR LISTA DE MATERIAS
@router.route('/registrarMateria')
def ver_guardarMateria():

PIS/templates/tempsAdmin/gestion/asignacion.html
{% extends 'tempsAdmin/index.html' %}
{% block content %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>

<div class="custom-container mt-5">
    <div class="card shadow-lg p-4">
        <h3 class="text-black text-center mb-4 fw-bold">Asignar Docente a Materia</h3>
        <form method="POST" action="{{ url_for('router.asignarMaestro') }}">
            <div class="mb-3">
                <label for="docente" class="form-label">Selecciona el Docente:</label>
                <select id="docente" name="docente" class="form-select" required>
                    <option value="" disabled selected>Selecciona un docente</option>
                    {% for docente in docentes %}
                        <option value="{{ docente._id }}">{{ docente._nombre }} {{ docente._apellido }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="mb-3">
                <label for="materia" class="form-label">Selecciona la Materia:</label>
                <select id="materia" name="materia" class="form-select" required>
                    <option value="" disabled selected>Selecciona una materia</option>
                    {% for materia in materias %}
                        <option value="{{ materia._id }}">{{ materia._nombre }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="text-center">
                <button type="submit" class="btn btn-primary">Asignar</button>
            </div>
        </form>

        <!-- Mostrar asignaciones con nombres -->
        <h3 class="text-black text-center mt-5 mb-4 fw-bold">Asignaciones</h3>
        <div class="d-grid gap-2 d-md-flex justify-content-md-end mb-3">
            <input type="text" id="searchInput" class="form-control me-2" onkeyup="searchTable()"
                placeholder="Buscar por letra o nombre completo ...">
            <select id="sortSelect" class="form-select me-2" onchange="sortTable()">
                <option value="docente-asc">Ordenar por Docente (Ascendente)</option>
                <option value="docente-desc">Ordenar por Docente (Descendente)</option>
                <option value="materia-asc">Ordenar por Materia (Ascendente)</option>
                <option value="materia-desc">Ordenar por Materia (Descendente)</option>
            </select>
        </div>
        <table id="tabla" class="table">
            <thead>
                <tr>
                    <th>ID Asignación</th>
                    <th>Docente</th>
                    <th>Materia</th>
                    <th>Ciclo</th>
                </tr>
            </thead>
            <tbody>
                {% for asignacion in asignaciones %}
                <tr>
                    <td>{{ asignacion[0] }}</td>
                    <td>{{ asignacion[1] }}</td>
                    <td>{{ asignacion[2] }}</td>
                    <td>{{ asignacion[3] }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<script>
    function searchTable() {
        var input, filter, table, tr, td, i, txtValue, fullName;
        input = document.getElementById("searchInput");
        filter = input.value.toUpperCase();
        table = document.getElementById("tabla");
        tr = table.getElementsByTagName("tr");
        for (i = 1; i < tr.length; i++) {  // Start from 1 to skip the header row
            td = tr[i].getElementsByTagName("td");
            if (td) {
                var docente = td[1].textContent || td[1].innerText; // Docente column
                var materia = td[2].textContent || td[2].innerText; // Materia column
                fullName = docente.toUpperCase(); // Combine name and surname
                
                if (fullName.indexOf(filter) > -1 || materia.toUpperCase().indexOf(filter) > -1) {
                    tr[i].style.display = "";
                } else {
                    tr[i].style.display = "none";
                }
            }
        }
    }

    function sortTable() {
        var table, rows, switching, i, x, y, shouldSwitch, sortOption;
        table = document.getElementById("tabla");
        switching = true;
        sortOption = document.getElementById("sortSelect").value;
        while (switching) {
            switching = false;
            rows = table.rows;
            for (i = 1; i < (rows.length - 1); i++) {
                shouldSwitch = false;
                if (sortOption === 'id-asc' || sortOption === 'id-desc') {
                    x = rows[i].getElementsByTagName("TD")[0]; // Index 0 for "ID Asignación" column
                    y = rows[i + 1].getElementsByTagName("TD")[0];
                } else if (sortOption === 'docente-asc' || sortOption === 'docente-desc') {
                    x = rows[i].getElementsByTagName("TD")[1]; // Index 1 for "Docente" column
                    y = rows[i + 1].getElementsByTagName("TD")[1];
                } else if (sortOption === 'materia-asc' || sortOption === 'materia-desc') {
                    x = rows[i].getElementsByTagName("TD")[2]; // Index 2 for "Materia" column
                    y = rows[i + 1].getElementsByTagName("TD")[2];
                }
                
                if ((sortOption === 'id-asc' && Number(x.innerHTML) > Number(y.innerHTML)) ||
                    (sortOption === 'id-desc' && Number(x.innerHTML) < Number(y.innerHTML)) ||
                    (sortOption === 'docente-asc' && x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) ||
                    (sortOption === 'docente-desc' && x.innerHTML.toLowerCase() < y.innerHTML.toLowerCase()) ||
                    (sortOption === 'materia-asc' && x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) ||
                    (sortOption === 'materia-desc' && x.innerHTML.toLowerCase() < y.innerHTML.toLowerCase())) {
                    shouldSwitch = true;
                    break;
                }
            }
            if (shouldSwitch) {
                rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
                switching = true;
            }
        }
    }
</script>

<style>
    body {
        background-color: #f8f9fa;
    }

    .custom-container {
        max-width: 1100px;
        margin: auto;
        background-color: #fff;
        border-radius: 10px;
        padding: 20px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }

    .card {
        border: none;
        border-radius: 1rem;
    }

    h3 {
        font-size: 24px;
        color: #343a40;
    }

    .btn {
        border-radius: 1rem;
    }

    .btn-primary {
        background-color: #007bff;
        color: #fff;
    }

    .table {
        width: 100%;
        margin-bottom: 1rem;
        color: #212529;
    }

    .table th,
    .table td {
        text-align: center;
        vertical-align: middle;
    }

    .thead-dark th {
        background-color: #343a40;
        color: #fff;
    }

    .form-control,
    .form-select {
        border-radius: 1rem;
    }

    @media (max-width: 768px) {
        .d-md-flex {
            flex-direction: column;
        }

        .me-2 {
            margin-bottom: 10px;
        }

        .custom-container {
            padding: 10px;
        }
    }
</style>
{% endblock %}